blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://github.com/CatOS-Scratch/CatOS/discussions/new?category=Help
    about: Get help
  - name: Ideas
    url: https://github.com/CatOS-Scratch/CatOS/discussions/new?category=Ideas
    about: Share your ideas
  - name: Feedback
    url: https://github.com/CatOS-Scratch/CatOS/discussions/new?category=Feedback
    about: Share your feedback
  - name: Discussions
    url: https://github.com/CatOS-Scratch/CatOS/discussions/
    about: Our forums
